let mapleader = "\\"

if executable("node") == 1
  let g:use_coc_nvim = 1
endif

call plug#begin('~/.vim/plugged')

if exists("g:use_coc_nvim") && g:use_coc_nvim == 1
  Plug 'neoclide/coc.nvim', { 'branch': 'release' }
endif

Plug 'dracula/vim'
Plug 'scrooloose/nerdtree'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'raimondi/delimitmate'
Plug 'yuezk/vim-js'
Plug 'maxmellon/vim-jsx-pretty'

call plug#end()

if exists("g:use_coc_nvim") && g:use_coc_nvim == 1
  source ~/.vim/coc.nvim.vim

  let g:coc_global_extensions = [
    \ 'coc-tsserver',
    \ 'coc-eslint',
    \ 'coc-stylelint',
    \ 'coc-json',
    \ 'coc-prettier',
    \ 'coc-yaml',
    \ 'coc-pyright',
    \ ]
endif

" Terminal
set splitright
set splitbelow
tnoremap <Esc> <C-\><C-n>
autocmd BufEnter * if &buftype == 'terminal' | :startinsert | endif
function! OpenTerminal()
  split term://bash
  resize 10
endfunction
nnoremap <silent> <C-n> :call OpenTerminal()<CR>

" Window navigation
tnoremap <A-Left>  <C-\><C-n><C-w>h
tnoremap <A-Down>  <C-\><C-n><C-w>j
tnoremap <A-Up>    <C-\><C-n><C-w>k
tnoremap <A-Right> <C-\><C-n><C-w>l
nnoremap <A-Left>  <C-w>h
nnoremap <A-Down>  <C-w>j
nnoremap <A-Up>    <C-w>k
nnoremap <A-Right> <C-w>l

" File Explorer
let g:NERDTreeShowHidden = 1
let g:NERDTreeMinimalUI = 1
let g:NERDTreeStatusline = ''
autocmd BufEnter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
nnoremap <silent> <C-f> :NERDTreeToggle<CR>

" Search
nnoremap <C-p> :FZF<CR>
nnoremap <silent> <leader>l :nohlsearch<CR>
let g:fzf_action = {
  \ 'ctrl-t': 'tab split',
  \ 'ctrl-s': 'split',
  \ 'ctrl-v': 'vsplit',
  \ }

" Theme
if has("termguicolors")
  set termguicolors
endif
syntax enable
if !empty(globpath(&rtp, 'colors/dracula.vim'))
  colorscheme dracula
endif

filetype plugin indent on

" Editor
set hidden
set number
set expandtab
set tabstop=2
set shiftwidth=2
set ignorecase
set smartcase
set scrolloff=8
set wildmode=longest,list
set fileformats=unix,dos
set clipboard^=unnamed,unnamedplus
set mouse=
set colorcolumn=80
set statusline=%f%m%=%l:%c\ %p%%

" Persistent undo
set undofile
set undodir=~/.vim/undo
autocmd BufWritePre * if !isdirectory(&undodir) | call mkdir(&undodir, 'p') | endif

" File-specific
autocmd FileType python setlocal tabstop=4 shiftwidth=4
autocmd FileType make setlocal noexpandtab

autocmd BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
